---
title: "On the origin of citations"
author: "Karlynn Neu"
date: "September 15, 2015"
output: 
        html_document:
                toc: true
                number_sections: true
                theme: cerulean
                highlight: espresso
                fig_width: 8
                fig_height: 8
                fig_caption: yes
---

# Load the data

## using read.delim

```{r load_data}
counts_raw <- read.delim("data/counts-raw.txt.gz")
counts_norm <- read.delim("data/counts-norm.txt.gz")
```

# Data exploration

What is the distribution of authors in all articles of our data set?
```{r author_histogram, echo=FALSE, fig.cap="Figure1: Number of Authors per article"}
hist(counts_raw$authorsCount, main = "Authors per paper", xlab = "# authors")
```

How popular are articles on Facebook?
```{r article_histogram, fig.cap="Figure2: Number of Facebook shares per article", echo=FALSE}
hist(counts_raw$facebookShareCount, main = "Shares per article", xlab = "# shares")

```

The average number of Facbook shares per paper in the data set is: `r mean(counts_raw$facebookShareCount)`




